// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH19YJbBU-1CkgiyUMqdaQZTnO_Ux21k8',
    appId: '1:354234419506:web:52b846d769f831f8ceaf2b',
    messagingSenderId: '354234419506',
    projectId: 'aquascale-36cc0',
    authDomain: 'aquascale-36cc0.firebaseapp.com',
    databaseURL: 'https://aquascale-36cc0-default-rtdb.firebaseio.com',
    storageBucket: 'aquascale-36cc0.firebasestorage.app',
    measurementId: 'G-C6FRMG4N77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsQ967_S6PGtNGBf2AiEjhG4JrrDGprQM',
    appId: '1:354234419506:android:68043157a525501eceaf2b',
    messagingSenderId: '354234419506',
    projectId: 'aquascale-36cc0',
    databaseURL: 'https://aquascale-36cc0-default-rtdb.firebaseio.com',
    storageBucket: 'aquascale-36cc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8otTCP8l_H2OSjt-A4bvxsSFscUkZpPM',
    appId: '1:354234419506:ios:40cef248448ea052ceaf2b',
    messagingSenderId: '354234419506',
    projectId: 'aquascale-36cc0',
    databaseURL: 'https://aquascale-36cc0-default-rtdb.firebaseio.com',
    storageBucket: 'aquascale-36cc0.firebasestorage.app',
    iosBundleId: 'com.example.aquascaleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8otTCP8l_H2OSjt-A4bvxsSFscUkZpPM',
    appId: '1:354234419506:ios:40cef248448ea052ceaf2b',
    messagingSenderId: '354234419506',
    projectId: 'aquascale-36cc0',
    databaseURL: 'https://aquascale-36cc0-default-rtdb.firebaseio.com',
    storageBucket: 'aquascale-36cc0.firebasestorage.app',
    iosBundleId: 'com.example.aquascaleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH19YJbBU-1CkgiyUMqdaQZTnO_Ux21k8',
    appId: '1:354234419506:web:e2bc17b818e8f48bceaf2b',
    messagingSenderId: '354234419506',
    projectId: 'aquascale-36cc0',
    authDomain: 'aquascale-36cc0.firebaseapp.com',
    databaseURL: 'https://aquascale-36cc0-default-rtdb.firebaseio.com',
    storageBucket: 'aquascale-36cc0.firebasestorage.app',
    measurementId: 'G-QZQY91J8NT',
  );
}
